### ISSUE TITLE
Adapt Code of Conduct

### ISSUE THREAD

**Issue by nsoranzo** [elixir-europe/rdm-toolkit#11]
- [x] Replace references to `Turing Way` and committee member names
- [x] Cite the original document URL
- [x] Compare with ELIXIR CoC
- [x] Set up/use an email address that can be used to report CoC violations

**Comment by CaroleGoble** [comment]
I made a first stab at this

**Comment by nsoranzo** [comment]
Thanks @CaroleGoble , looks much better! I feel it's a bit confusing when one should contact the Toolkit Code of Conduct Allies and when the ELIXIR Code of Conduct Oversight Group, and what the 2 groups are responsible for.
I suppose the distinction comes from https://drive.google.com/file/d/1IM5ePgR2JI48gU_Sgow5n2HTb28NTbl0/view , but maybe it's not needed outside of events.

**Comment by CaroleGoble** [comment]
yes - the allies bit might just apply to events. but maybe having some dedicated CoC people in this community is a good idea

**Comment by nsoranzo** [comment]
Agreed, we can have Allies as first point of contact (unless involved in the incident) and leave the Oversight Group deal with appeals and violations by Allies. In that case we don't need to involve the busy Director.

**Comment by CaroleGoble** [comment]
except that this the Director is explicitly included in the ELIXIR CoC.

**Comment by bedroesb** [comment]
email address was added #192

**Comment by bedroesb** [comment]
New TODO: 
- [ ] any reference to the ELIXIR Oversight Group and/or reporting procedures needs to be fully replaced with the RDM procedure
- [ ] removing the option to circumvent the RDM Oversight Group and report to Niklas/Susanna
