### ISSUE TITLE
'Contributing' feedback

### ISSUE THREAD

**Issue by martin-nc** [elixir-europe/rdm-toolkit#112]
I've had a go at the Contribute pages and here is my feedback.

**[Contribute page](https://rdm.elixir-europe.org/how_to_contribute.html)**:

- [x] - Do we need the summary at the top? I don't think so. I find it distracting because it says "please follow the links on the left", and so discourages you from reading the page!
- [x] - Flow diagram: it would be nice if this was in the brand colours, and the boxes were links (at least to the two ways of contributing). I could have a go at redrawing it but not sure if I'll have time before the hackathon.

**[GitHub way page](https://rdm.elixir-europe.org/github_way.html)**:
 - I got lost with all the links in this page.
    - [x] I'd suggest removing the 'Go the RDM toolkit website' links, because you are already on the website! I'd make the link go to where people need to go (the issues page etc) and maybe mention "You can also get to this page using the 'GitHub' link in the header of this site".
    - [x] I found the links to the GitHub documentation pages confusing. 'Preview here' didn't make sense to me: what am I previewing? I hadn't done anything to preview. Also phrases like "Open a [link]Draft pull request[/link]" suggest you should click on the link to open a draft pull request, but you don't. You get taken to a GitHub documentation page. You could change the link text to "See the GitHub documentation" but I think it's better to remove links to GitHub documentation altogether. Perhaps there can be a section at the end with links to it. We need people to follow one simple path: we open the issues page in a new tab for them in the first link, and then we give them no more links. They need the documentation page open plus the issues page open, and no more links to muddle them and take them away from the task in hand.
    - [x] Little screenshots of the buttons would be good but I don't know if there will be time before the contentathon.
    - [x] I didn't know what a 'Demo page' was. I couldn't think what it would be demonstrating. I'd call the demo page a 'Formatting guide' or 'Code reference' page.

**[Google Doc way](https://martin-nc.github.io/martinc-rdm-toolkit/google_doc_way.html)**
 - [x] I wonder if we need the diagram at the top? It feels like an internal document to me. If people are going to that page because they are frightened of GitHub then perhaps the diagram will frighten them as well! It looks quite complicated. Perhaps we need the process to look simple?
 - [ ] What does someone do if they only want to suggest a small change to a page? The Google Doc way suggests that it's for large text inserts, like new pages, rather than editing existing pages.

Anyway, those were just my thoughts. I'll see if I can get other people to try it all out.

**Comment by pinarpink** [comment]
Thanks @martin-nc . I agree with all your suggestions. We will have to apply some and leave others for later due to the imminent contentathon.

**Comment by frederikcoppens** [comment]
Claiming of an existing issue needs to be added to https://rdm.elixir-europe.org/how_to_contribute.html
Propose to 1) assign yourself and 2) leave a comment to clarify if applicable

**Comment by frederikcoppens** [comment]
The current process comes across as very linear: first discuss, then write content. Which could end up discouraging people to add content. I would encourage people to discuss and comment, but enable/stimulate them to provide content (in a PR or doc) in parallel too. If we have their attention, we should make use of it directly. 

For the Google doc way: can we add a link to a (read-only) template people can use ? 
For the GitHub way: I would drop "When you and the editors have agreed on the type of contribution," and phase this more welcoming

**Comment by frederikcoppens** [comment]
We are missing some info on copyright guidelines, to make sure people 1) realise all content here is CC4-BY and 2) they should properly attribute when they reuse content from other places. @martin-nc is working on an 'copyright guideline' doc to refer to

**Comment by martin-nc** [comment]
Copyright guide is now here: https://rdm.elixir-europe.org/copyright.html.

**Comment by bedroesb** [comment]
@martin-nc and @pinarpink I think the last point that had to be done here is covered by https://rdm.elixir-europe.org/how_to_contribute.html#contributor-responsibilities ? Are still things we need to do here?

**Comment by pinarpink** [comment]
@bedroesb I think the last point is covered with recent change of contribute pages. so good to close IMO.

**Comment by martin-nc** [comment]
Yes, I think the new form covers that.
