### ISSUE TITLE
New page on privacy techniques for research data

### ISSUE THREAD

**Issue by pinarpink** [elixir-europe/rdm-toolkit#116]
**What topic do you wish to add?**
Please provide a brief description.

I think the RDM toolkit website needs a page on pseudonymisation and anonymisation tools.

**Are there existing pages in the RDM toolkit website related to the requested page?**
I have not seen any.

**Resources**
If there are there resources that could be utilised for writing the new page, please list them below:

ARX anonymiser website is useful.
...

**Context**
If this request is coming from a particular project, domain, or use-case please list them below:

This page will ned to be linked to the Human Data use case.

**Comment by floradanna** [comment]
good idea. I will make the page.

**Comment by floradanna** [comment]
The new page is here: https://github.com/elixir-europe/rdm-toolkit/blob/master/pages/functional_areas/Privacy.md
