### ISSUE TITLE
Suggestion on the "Your problem" section

### ISSUE THREAD

**Issue by floradanna** [elixir-europe/rdm-toolkit#127]
**Description**
@DanFaria  and I propose to add new pages to be shown under "Your problem" section, in the sidebar of the website. 
These pages should refer to broad topics, so that more specific problems can be added later as subpages.
Showing additional "broad topic pages" could help contributors better identify the needed guideline and content.
The proposed page titles below are based on the questions listed in "Your role" pages.

- Ethics and legality: templates for legal and policy documents, IP, confidentiality agreement, agreement between institutions, ...
- Funders' requirements: DMP templates, data availability policy, ...
- Data organisation: folder structure, file naming, versioning, ...
- Data sharing: repositories, licence, ...
- Data analysis: reproducible analysis pipeline, workflow, ...
- Data processing: data quality control, ...

(Already there) Data storage: estimate data volume, storage during the project, storage after the project, computational storage, costs, ...
(Already there) Metadata management: ontology, data documentation (README), ...
(Already there) Security & privacy: data access control, personal and sensitive data, ...
(Already there) Data sustainability: data preservation, data archiving, file format, identifier, archiving, ...
(Already there) Compliance monitoring and measurement: ...
(Already there) Data transfer: from provider to compute resource, ...

I would also suggest to:
1) Explain somewhere the sub-topics expected under each "broad topic page" in Your problem section.
2) Keep only "Data security" (data access control) and address "Privacy" in Human Data domain to avoid repetition.
3) Rename "Data sustainability" with a more clear term (is it the same of data preservation or archiving?)
4) Think about guideline for management of software (metadata, licence, repositories, versioning, etc): it could go in "Your domain", or could be treated as any other data type, or could have a dedicated page under "Your problem".

**Comment by CaroleGoble** [comment]
Same for industrial biotechnology and intellectual property

Carole

**Comment by pinarpink** [comment]
dear @floradanna

-  I think the question of "which page goes where" will also be something editors need to figure out once we to obtain some content.
- I understand your intent in adding "data organisation, sharing...." , however, instead of adding menu items, I'd be more inclined to point to them the [FAQ sheet](https://docs.google.com/spreadsheets/d/1VXhSE2le0J5TAUZY9Se3mb2JACUg0vavGoJML0BlakY/edit#gid=595378500) of the tools inventory. This way they can try to see which under which heading the page they will write may fall.  Shall I create an MoM document in break out folders and put there  the link to tool inventory?

**Comment by floradanna** [comment]
Hi @pinarpink 
This is also a good option. I will also add the link to the tools inventory in the agenda.

**Comment by OlivierCollin** [comment]
Maybe point 4 can be considered under a "computational reproducibility" topic in the "your problem" section  ? Or is it opening a Pandora's box ?
