### ISSUE TITLE
privacy page is needed

### ISSUE THREAD

**Issue by pinarpink** [elixir-europe/rdm-toolkit#130]
**What topic do you wish to add?**
Please provide a brief description.

**Are there existing pages in the RDM toolkit website related to the requested page?**

**Resources**
If there are there resources that could be utilised for writing the new page, please list them below:

**Context**
If this request is coming from a particular project, domain, or use-case please list them below:

**Comment by bedroesb** [comment]
Thank you for you contribution !

**Comment by bedroesb** [comment]
We have discussed and approved this new page request within the editors.
An empty page to work on can be found at: https://rdm.elixir-europe.org/privacy

**Comment by bedroesb** [comment]
I will also close this issue for the sake of the Demo
