### ISSUE TITLE
[DEMO] Privacy and pseudonymization page is needed.

### ISSUE THREAD

**Issue by pinarpink** [elixir-europe/rdm-toolkit#134]
**What topic do you wish to add?**
Please provide a brief description.

Privacy tools neeed introduction with a sample problem and links.

**Are there existing pages in the RDM toolkit website related to the requested page?**
I have checked and have not seen any pages.

**Resources**
If there are there resources that could be utilised for writing the new page, please list them below:

BBMRI ELSI Knowledge BAse is a good resource to look up when writing this page.

**Context**
If this request is coming from a particular project, domain, or use-case please list them below:

**Comment by floradanna** [comment]
Good idea. Here is the page: https://rdm.elixir-europe.org/privacy

**Comment by bedroesb** [comment]
This was a demo issue and will be closed
