### ISSUE TITLE
Copyright page?

### ISSUE THREAD

**Issue by martin-nc** [elixir-europe/rdm-toolkit#136]
**What topic do you wish to add?**
We probably need a page for website copyright.

**Are there existing pages in the RDM toolkit website related to the requested page?**
No.

**Resources**
If there are there resources that could be utilised for writing the new page, please list them below:

**Context**
If this request is coming from a particular project, domain, or use-case please list them below:

**Comment by bedroesb** [comment]
Heloo Martin!
great idea
I made you a page at: https://rdm.elixir-europe.org/COPYRIGHT

**Comment by bedroesb** [comment]
I don't know if we want to put it in the root of the directory or in the pages one
