### ISSUE TITLE
Adding custom GitHub labels for Issues and PRs

### ISSUE THREAD

**Issue by frederikcoppens** [elixir-europe/rdm-toolkit#14]
Useful to have labels to categorise issues, next to the default that GitHub provides ?

Suggestions (inspired by the Turing way):

Project management
Community
Tools
Typo-fix (Fix a typo or a broken link, make the project better)
Work-in-progress
Idea-for-discussion (This can be used for inviting discussion from collaborators or community in general)
Outreach
UI-UX
Personas

**Comment by bedroesb** [comment]
Personas will be one of the section specific labels?

**Comment by CaroleGoble** [comment]
yes

**Comment by bedroesb** [comment]
I added topic specific label. I guess this issue can be closed? @frederikcoppens
