### ISSUE TITLE
Biomolecular Simulation Data

### ISSUE THREAD

**Issue by adamhospital** [elixir-europe/rdm-toolkit#140]
**What topic do you wish to add?**
New Domain related to Biomolecular Simulation Data.

**Are there existing pages in the RDM toolkit website related to the requested page?**
No

**Resources**
If there are there resources that could be utilised for writing the new page, please list them below:
N/A

**Context**
If this request is coming from a particular project, domain, or use-case please list them below:
WP5 use case about Biomolecular Simulation Data

**Comment by DanFaria** [comment]
Here is the page: https://github.com/elixir-europe/rdm-toolkit/blob/master/pages/your_domain/biomolecular_simulation_data.md

**Comment by KarelBerka** [comment]
webpage is available at https://rdm.elixir-europe.org/biomolecular_simulation_data 
But no links are active and there it is not linked from the main webpage yet.

**Comment by DanFaria** [comment]
Hi @KarelBerka,
We will be going over the new pages and linking them in our next WP3 meeting.
