### ISSUE TITLE
IDP use case

### ISSUE THREAD

**Issue by ivanmicetic** [elixir-europe/rdm-toolkit#141]
**What topic do you wish to add?**
Please provide a brief description.

IDP use case "Your domain" page. It would deal with IDP user community related processes

**Are there existing pages in the RDM toolkit website related to the requested page?**
No

**Resources**
If there are there resources that could be utilised for writing the new page, please list them below:

**Context**
If this request is coming from a particular project, domain, or use-case please list them below:
IDP user community

**Comment by DanFaria** [comment]
Here is the page: https://github.com/elixir-europe/rdm-toolkit/blob/master/pages/your_domain/intrinsically_disordered_proteins.md
