### ISSUE TITLE
First draft for the Storage Solutions Page

### ISSUE THREAD

**Issue by smza** [elixir-europe/rdm-toolkit#142]
**Link to the page of interest**
https://rdm.elixir-europe.org/storage.html

**Describe what you would change to the page**
We are planning to write the content for the storage solutions.

**List the tool(s)or resource(s) that are missing on the page (if applicable)**
- Name
- Link
- Description
- Registry (biotools or/and fairdome ID) (optional)

**Comment by bedroesb** [comment]
@smza was this covered in the contentathon Otherwise we can close this issue I think  :)

**Comment by smza** [comment]
> @smza was this covered in the contentathon Otherwise we can close this issue I think :)

I think we need more discussions around this page to make sure whether the content is appropriate.

**Comment by bedroesb** [comment]
I think the 'first draft' is reached and will be further improved by #259 #262
