### ISSUE TITLE
Add Training column to tools table to enable Tess search for tools

### ISSUE THREAD

**Issue by pinarpink** [elixir-europe/rdm-toolkit#145]
**Link to the page of interest**
The tools table may be extended with Tess as a registry, similar to bio tools.

**Describe what you would change to the page**

We need a column which contains a clickable Tess link

**List the tool(s)or resource(s) that are missing on the page (if applicable)**
- Name
- Link
- Description
- Registry (biotools or/and fairdome ID) (optional)

**Comment by pinarpink** [comment]
After some discussion we realised that searches for training per tool mostly returns empty results on Tess, so rather than adding search per row in the tools table we may need to look into search per LifeCycle stage or Problem Area.

**Comment by christopherchild** [comment]
It was also mentioned that it might be possible to have an automated check using the TeSS API to ensure the quality of the links. i.e. make sure that the search does return some results rather than linking to an empty search
