### ISSUE TITLE
Attribution of contributors : how ?

### ISSUE THREAD

**Issue by frederikcoppens** [elixir-europe/rdm-toolkit#18]
In The Turing Way this is detailed in the 
https://github.com/alan-turing-institute/the-turing-way/blob/master/GOVERNANCE.md

Is this the default naming for this ? As I do not associate governance with authorship e.g.
We do want to explain how we recognise contributions

**Comment by bedroesb** [comment]
Contributors will be listed on page level and be mentioned in the upcoming hall off fame carousel on the landing page / or about
