### ISSUE TITLE
TeSS/Training link in tools and resources table

### ISSUE THREAD

**Issue by christopherchild** [elixir-europe/rdm-toolkit#181]
We were discussing again (@vdda and @celiavg) the possibility of having a link in the tools and resources table. We thought it would be useful to open the discussion up.

I know we decided yesterday against the idea, because we didn't want to have links through to search queries with no results. 

What if instead of having a link for all tools, we did the same as for the bio.tools and specificity put links to training when we know a good set of materials are available.

For example:
We know GitHub has a good number of materials listed in TeSS, so it would make sense to have a link in the registry column.

![image](https://user-images.githubusercontent.com/996720/96258979-cba43b80-0fb4-11eb-9462-706a22127f7b.png)

**Comment by bedroesb** [comment]
but I guess Tess is here different than the other since its results are variable, while with bio.tools and FAIRsharing it is a perminant id we link too

**Comment by bedroesb** [comment]
How we will implement this is listed in this issue: #228
