### ISSUE TITLE
How to contribute

### ISSUE THREAD

**Issue by frederikcoppens** [elixir-europe/rdm-toolkit#19]
Inspiration 

https://github.com/alan-turing-institute/the-turing-way/blob/master/CONTRIBUTING.md
https://fairplus.github.io/the-fair-cookbook/Contributing.html

From discussions:
Three contributor pathway levels
Upper - using github directly, using markdown templates, assigning tags, pull requests to notify editors
Middle - using googledoc templates, simple raising issues and notifying editors, simple markdown add to pre-existing pages
Lower - using googledoc templates, emailing editors ro submitting a notification through a form.

**Comment by nsoranzo** [comment]
xref. https://github.com/elixir-europe/rdm-toolkit/issues/3

**Comment by nsoranzo** [comment]
However a contribution reaches GitHub, should we mandate use of Pull Requests and prevent direct pushing to `master`?

**Comment by bedroesb** [comment]
this is covered in the contributing section of the website https://rdm.elixir-europe.org/how_to_contribute.html
