### ISSUE TITLE
Create an email address for the Code of Conduct

### ISSUE THREAD

**Issue by martin-nc** [elixir-europe/rdm-toolkit#192]
We probably need an email address for people to use if they feel the Code of Conduct has been breached. Perhaps rdm-coc@elixir-europe.org. I can create this.

**Comment by martin-nc** [comment]
The mail address now exists: rdm-coc@ellixir-europe.org. It includes Hannah from the Hub, plus @DanFaria, @frederikcoppens  and @CaroleGoble. We can now add this address to the website. Let me know if anyone else should be included (or removed).

**Comment by bedroesb** [comment]
@martin-nc that is great! I guess we can close this pull request?

**Comment by martin-nc** [comment]
@bedroesb Yes, I guess we can close the issue. I was just waiting to see if any other names were suggested for the email list.
