### ISSUE TITLE
Adding some information about the all tools and resources list

### ISSUE THREAD

**Issue by bedroesb** [elixir-europe/rdm-toolkit#203]
**Link to the page of interest**
https://rdm.elixir-europe.org/all_tools_and_resources.html

**Describe what you would change to the page**

I think it needs an introduction or something. That this is a curated list of the tools mentioned in our sections etc ...

**Comment by Drosophilic** [comment]
The link doesn't seem to work for me.

**Comment by bedroesb** [comment]
@Drosophilic fixed!
