### ISSUE TITLE
Page for Submitting your data to a public repository under the Your Problem section

### ISSUE THREAD

**Issue by smza** [elixir-europe/rdm-toolkit#206]
**What topic do you wish to add?**
As discussed during the contentathon we want to have a separate page for information on public repositories.

**Are there existing pages in the RDM toolkit website related to the requested page?**
NO

**Resources**
https://wellcomeopenresearch.org/for-authors/data-guidelines
https://www.nature.com/sdata/policies/repositories

**Context**
If this request is coming from a particular project, domain, or use-case please list them below:

**Comment by bedroesb** [comment]
@smza is there already an appropriate page made for this request?
