### ISSUE TITLE
Suggestion for improving the Contribute page

### ISSUE THREAD

**Issue by martin-nc** [elixir-europe/rdm-toolkit#208]
Here is a quicker suggestion for improving the [contribute page](https://rdm.elixir-europe.org/how_to_contribute.html) (see @frederikcoppens comments in https://github.com/elixir-europe/rdm-toolkit/issues/112). First, have a welcome message saying something like: "Everyone is welcome to contribute to this site, and we've tried to make it as easy as possible. Choose a way that suits you. The website is hosted on GitHub, so:".

 1. **If you are not familiar with GitHub but want to give it a try:** follow our [step-by-step instructions](https://rdm.elixir-europe.org/github_way.html) (no technical knowledge required!).
 2. **If you are happier using Google Docs:** follow the [Google Doc way](https://rdm.elixir-europe.org/google_doc_way.html).
 3. **If you are familiar with Github:** fork the [repo](https://github.com/elixir-europe/rdm-toolkit) and create a pull request.
 4. **If you just want to make a quick contribution:** submit your comments/suggestions using the form below.

The form could  be an embedded Google Form in the same page. If people are in the middle of something and just want to make a quick suggestion or amendment, they don't have to to through the palaver of reading about the other approaches. The form could capture what type of suggestion they're making (new page/ correction/ tool addition etc) and ask for the page they're referring to (if relevant). Then the form creates an issue using [Fire](https://fire.fundersclub.com/) or [Zapier](https://zapier.com/) (the Hub has an account with the latter). 

I'm afraid this means Bert's flowchart goes, but at least it solves the usability issue! (Confession: I suggested the diagram links in #112, but it was a bad idea!)

**Comment by martin-nc** [comment]
@pinarpink To set up the 'zap' between the Google form and GitHub, I need to sign in to the Google form from Zapier. Was it set up under a generic Google account?

**Comment by pinarpink** [comment]
@martin-nc I designed the form with my google account. I had shared the form with @bedroesb and @floradanna would you be able to see it in Zapier if I add you to the share? Otherwise we would need to redesign the form with the Hub's google account.

**Comment by martin-nc** [comment]
@pinarpink Let's try the sharing option. Could you share the form with me, at least until I set 'zap' up?

**Comment by martin-nc** [comment]
I've set the Zapier integration up now. When you submit the form it creates a new issue. The title of the issue is "A new suggestion from ['Name' field in the form]". The description in the issue is the 'Your comment or suggestion' field in the form. Let me know if you want anything changing there. Bear in mind that Zapier checks the form responses every 15 minutes, so issues will not appear instantly once the form has been submitted.

I see the email field in the form is mandatory - is that necessary?  Perhaps it would be good to **not** collect personal data if we didn't have to.  Perhaps we can make it non-mandatory and say, "Please leave your email so that we can contact you about your suggestion if necessary. Your email will only be held for this purpose, and will be removed from our records once your suggestion has been processed." Or something like that.

We'll have to watch for spam in this form. I don't know if Google have anything built-in to prevent it.

**Comment by pinarpink** [comment]
ok will make email optional

**Comment by pinarpink** [comment]
and thanks a lot Martin!

**Comment by bedroesb** [comment]
@pinarpink @martin-nc This system is up and running and the changes are applied if I recall correctly?
