### ISSUE TITLE
Ensure a consistent colour scheme for the site

### ISSUE THREAD

**Issue by martin-nc** [elixir-europe/rdm-toolkit#23]
Change the current template to ELIXIR colours? Most of the template should remain white so I'm not suggesting a frenzy of orange. The colour scheme should apply to illustrations as well as to the coloured elements on the page. Main ELIXIR colours:

- Orange: #f47d21
- Dark blue: #023452

There are also lighter blues and a green (BEWARE: it looks hideous with the orange). Finally there is grey as well. Can post the hex codes for them all if required.

**Comment by bedroesb** [comment]
Are there fonts that we could use? 
First try with the colors:
![image](https://user-images.githubusercontent.com/44875756/86897015-2bae5a80-c107-11ea-986d-93475b1cb924.png)

**Comment by bedroesb** [comment]
The grey is #efefef taken from the elixir website :)

**Comment by martin-nc** [comment]
Hi Bert! I'd use white text in the header because the contrast will be better (accessibility). Looking better, though! We use Lato on the main site. It's a free Google font.

**Comment by martin-nc** [comment]
If you're in the CSS, how about adding slightly more padding to the links in the left menu, to make each item slightly bigger? And maybe a couple pixels more space between the items?

**Comment by bedroesb** [comment]
Hopefully I didn't do to much padding:
![image](https://user-images.githubusercontent.com/44875756/86900937-41724e80-c10c-11ea-8711-58f510c13d62.png)

I also like the title above the left side panel in the elixir-europe website to identify the current section

**Comment by martin-nc** [comment]
Yes, maybe the font size was okay before. The extra padding looks good, I think. It just makes the items easier to tap with a finger, or even find with a mouse cursor. You don't need such fine motor control (important for accessibility, too e.g. people with arthritis in their hands).

**Comment by bedroesb** [comment]
based on #27 I think this can be closed?
