### ISSUE TITLE
Add description of expected to content to empty pages

### ISSUE THREAD

**Issue by pinarpink** [elixir-europe/rdm-toolkit#236]
**Pages that require updating**

- [Compliance Monitoring & Measurement](https://rdm.elixir-europe.org/compliance_monitoring_and_measurement.html): Assessing how fair a node service or a database is or tools to measure FAIRness.Also, compliance in the areas of security and data protection e.g. ISO 27001, GDPR Certification.
- [Data sustainability](https://rdm.elixir-europe.org/data_sustainability.html): Consider renaming to data quality.

**Comment by floradanna** [comment]
Thanks Pinar. I just wanted to add that if we give priority to this, there is an higher chance to find contributors for these pages during the next WP1 meeting on Monday 30 November 2020.

**Comment by pinarpink** [comment]
I created a PR for the quality page. Will create the PR for compliance this afternoon.

**Comment by floradanna** [comment]
Great, thank you Pinar. I notice that the "quality page" PR has a conflict because few days ago I also changed the yaml file. Let me know if you want me to look into the conflict.

**Comment by pinarpink** [comment]
@floradanna  I rebased, should be mergeable now.

**Comment by floradanna** [comment]
did you delete the changes I had done in the yaml file? Few days ago I renamed "Public repositories" into "Data sharing". Did you change it back into "Public repositories" in your PR? If yes, could you put it back as "Data sharing" please?

**Comment by pinarpink** [comment]
@floradanna I did not remove any "data management plan" anywhere if you look at the. If you see the [changes in the PR branch ](https://github.com/elixir-europe/rdm-toolkit/pull/239/files) there is no such thing.

**Comment by pinarpink** [comment]
@floradanna "Public repositories" changed to "Data sharing"

**Comment by floradanna** [comment]
@pinarpink Perfect, thank you. Do you want me to merge now?

**Comment by pinarpink** [comment]
sure, I will create another PR for compliance.
