### ISSUE TITLE
Use a proper domain name?

### ISSUE THREAD

**Issue by martin-nc** [elixir-europe/rdm-toolkit#24]
Maybe we want to use a subdomain name like 'rdm-toolkit.elixir-europe.org' (a bit long) or get a separate domain like 'rdm-toolkit.org', or stick with the current url (https://elixir-europe.github.io/rdm-toolkit/).

**Comment by bedroesb** [comment]
last day of hackathon we had a discussion about this of using rdm-toolkit.elixir-europe.org or elixir-europe.org/rdm-toolkit.
My original idea was to use a separate domain. But counter arguments were that the styling now is very elixir-ish, and therefor could fit under the europe domain...
I don't know how much this will influence the findability by google.

**Comment by martin-nc** [comment]
So was a definite decision made? I'll have to ask my boss at the hub if he's okay with the subdomain before I request it, if that's what people want. 

Whichever approach is taken, I don't think it should impact SEO much. The main thing is to have unique, interesting content. It's what the advice from all the search engines say e.g. [Google](https://support.google.com/webmasters/answer/35769?hl=en): "Think about what makes your website unique, valuable, or engaging. Make your website stand out from others in your field."

**Comment by martin-nc** [comment]
@bedroesb now the subdomain has been decided, we'll have to configure it. I'll probably request it on Monday. Just before I do that, though, we'll have to follow the instructions here for setting up subdomains: https://docs.github.com/en/github/working-with-github-pages/managing-a-custom-domain-for-your-github-pages-site. I assume we're okay to go ahead with it, and it doesn't need further discussion.

**Comment by bedroesb** [comment]
I think so to!

**Comment by bedroesb** [comment]
Let me know when would be appropriate to change the settings of the repo :)

**Comment by martin-nc** [comment]
@bedroesb Yes, just go ahead now. I'll request the subdomain.

**Comment by bedroesb** [comment]
is it possible that you will have to set up the DNS configuration? :)

**Comment by martin-nc** [comment]
The EBI web support team manage the ELIXIR domains so I have to ask them for any changes, which I've just done. We just need a CNAME record to point rdm.elixir-europe.org to elixir-europe.github.io. From there, hopefully GitHub will direct the request to the right repo!

I see that 'Enforce https' is now off for the repo. We'll have to make sure that is on when the subdomain starts working.

**Comment by bedroesb** [comment]
The HTTPS option is not yet available: Unavailable for your site because your domain is not properly configured to support HTTPS (rdm.elixir-europe.org) — Troubleshooting custom domains

**Comment by bedroesb** [comment]
I got this message 'Domain's DNS record could not be retrieved.'

**Comment by bedroesb** [comment]
By specifying the CMAKE in this repo (root), the site is already redirecting to rdm.elixir-europe.org. Or there other things I have to do? Besides #86

**Comment by martin-nc** [comment]
@bedroesb about the https: yes, I know. It won't work until the subdomain kicks in. When that happens, I don't think the https is turned back on automatically, so we have to do that manually. 

As for the DNS record - the subdomain hasn't been set up yet. I'm waiting for them to do it. If people need the site urgently then you'll have to undo the change in the settings. The trouble is, we have to do it in order: 1. Change the repo settings 2. Make the DNS changes. 

I think you've done all you need to do. We're just waiting for the EBI team. I see there's a status update on my ticket so hopefully it won't be long...

**Comment by bedroesb** [comment]
Great! Lets hope not, I notified that the page is unreachable :) Will turn on HTTPS as soon as it comes available.

**Comment by martin-nc** [comment]
It's working now: [http://rdm.elixir-europe.org/](http://rdm.elixir-europe.org/)

**Comment by bedroesb** [comment]
and now also with https on!
