### ISSUE TITLE
Contact email for the toolkit

### ISSUE THREAD

**Issue by martin-nc** [elixir-europe/rdm-toolkit#25]
Do we need a contact email specifically for the toolkit? I can create one like rdm-toolkit@elixir-europe.org if that is useful.  It will be a forwarding email, so it will forward to the WP mailing list or to individuals' addresses. It's up to you. You won't be able to send from this address, that's all.

Sorry if there already is an address!

**Comment by bedroesb** [comment]
Something to be added in the footer ?

**Comment by martin-nc** [comment]
Yes, and I was thinking at the bottom of the home page, too, as the last item in the main content area: "If you have any questions, feel free to email us at...".  If people are more likely to use a simple contact form then we could try one of these approaches:

- https://github.com/dwyl/learn-to-send-email-via-google-script-html-no-server#how
- https://jekyllthemes.io/resources/jekyll-contact-forms

**Comment by floradanna** [comment]
Could the "Give feedback" button, which is in the top navigation bar, be used by our readers to give general suggestions and ideas about the toolkit?

If yes, would it be possible to link the "Give feedback" button to the creation of an issue in GitHub directly?

**Comment by bedroesb** [comment]
@martin-nc now that we know that the domain will be rdm.elixir-europe.org,  can we assume we go for rdm@elixir-europe.org as main e-mail address?

**Comment by martin-nc** [comment]
That would be the easiest and quickest solution, if people are happy with that. If we wanted to use the subdomain (e.g. enquiries@rdm.elixir-europe.org) then we'd have to create some MX records for the subdomain.

**Comment by martin-nc** [comment]
I'm assuming rdm@elixir-europe.org would be a mailing list. It's probably an idea to decide what emails are needed and why they are needed e.g. you could have rdm-enquiries@elixir-europe.org for external people to ask questions, and rdm-editors@elixir-europe.org for the editorial group. But I'd keep email addresses to a minimum because we probably all get too many emails!

**Comment by bedroesb** [comment]
@martin-nc would it be a lot of work to get enquiries@rdm.elixir-europe.org?  If we ever want to distinguish with the emails:  one for feedback and one for content submission, it will maybe be easier... @pinarpink do you have a specific opinion ? or @nsoranzo ?

**Comment by martin-nc** [comment]
Actually, I'll need to check with the EBI if we can do the subdomain emails. They provide up with the mail servers. If people prefer the subdomain route then I can ask about it.

**Comment by pinarpink** [comment]
@bedroesb  the two addresses suggested by @martin-nc look good to me:

- **rdm-enquiries@elixir-europe.org**    for external people to ask questions
- **rdm-editors@elixir-europe.org**    to reach website editors

**Comment by bedroesb** [comment]
ok perfect!

**Comment by martin-nc** [comment]
Okay, I can create those addresses. Can you let me know who needs to be on each one? Is it:

1. rdm-enquiries: ?
2. rdm-editors: Frederik, Carole, Munazah, Pinar, Flora, Bert.

**Comment by martin-nc** [comment]
The second address has now been created (rdm-editors@elixir-europe.org).

**Comment by bedroesb** [comment]
thank you @martin-nc

**Comment by pinarpink** [comment]
thanks @martin-nc

**Comment by bedroesb** [comment]
@pinarpink do we need rdm-enquiries ? or can we close this issue
