### ISSUE TITLE
Proposal for a tagging system

### ISSUE THREAD

**Issue by floradanna** [elixir-europe/rdm-toolkit#252]
**Tags for “tools and resources”:**
Problems_tags = tags corresponding to (or having the same name of) “your problem” Pages
Domains_tags = tags corresponding to (or having the same name of) “your domain” Pages
Accessible_from_tags = tags in case of country-specific accessibility
_Maybe also Roles_tags = tags corresponding to (or having the same name of) “your role” Pages?_

**Tags for “your problem” Pages**
Stages_tags = tags corresponding to (or having the same name of) RDM Life cycle stages.
Roles_tags = tags corresponding to (or having the same name of) “your role” Page.

By using this system we could, automatically:
- list "your problem" pages under "related topics" at each RDM life cycle stage page.
- list "your problem" pages under "Pages you might be interested in" at each "your role" page [(as here](https://rdm.elixir-europe.org/research_it.html#pages-you-might-be-interested-in))
- list correct tools under your problem, domain (role?) page
- list tools and resources with country-specific accessibility in separate section dedicated to [country-specific advice](https://github.com/elixir-europe/rdm-toolkit/issues/196).

**Comment by bedroesb** [comment]
A first step towards this is done in #251

**Comment by floradanna** [comment]
Practical example of how to apply the proposed tagging system for tools/resources and problem pages.
[RDMtoolkit_tagging_system_v02.xlsx](https://github.com/elixir-europe/rdm-toolkit/files/5642421/RDMtoolkit_tagging_system_v02.xlsx)

**Comment by bedroesb** [comment]
Preview can be seen [here](https://bedroesb.github.io/rdm-toolkit)
