### ISSUE TITLE
Overall structure of the webpage

### ISSUE THREAD

**Issue by floradanna** [elixir-europe/rdm-toolkit#253]
I am raising this issue because I would like to discuss with all the editors the overall structure of this webpage. I believe that some decisions should be made in order to enable a smooth growth of the toolkit.

1) Since we are not defining/creating all pages of the toolkit upfront, we could add the recommendation to _“avoid manual linking to other pages of the toolkit"_ in the "how to contribute" and “style" pages. This is should limit the problem of having not functional links every time a page is deleted or renamed, and of adding links everywhere every time that a new page is created.
2) To help with the issue number 1 above, we could implement a more thoughtful [tagging system for pages](https://github.com/elixir-europe/rdm-toolkit/issues/252).
3) Since the content of each Page (shown in the sidebar under problem, domain etc..) starts to increase and to be more detailed, we have “sub-pages” linked to Page. This is currently not being thought of.  It would be wise to plan how this should happen upfront, otherwise editors could quickly loose the overview of the website and have issues with tagging for tools, roles…etc. Maybe, things that could be decided are:
- How many levels can we handle? We have Page (visible in sidebar), sub-pages in the Page, do we want to allow "sub-sub-pages in sub-page?
- Where do we save sub-pages in the GitHub repo: in the same folder of the Page or in different folder?
- Will tools be tagged only with Pages tags or also “sub-pages” tags?

I hope we can address these topics at the next editorial meeting.

**Comment by CaroleGoble** [comment]
This is a big topic you raise Flora! yes we should discuss this in the next meeting

**Comment by wna-se** [comment]
An additional measure to alleviate the first item could be adding a workflow task and instructions for [automatic checks for broken links](https://github.com/episource/jekyll-html-proofer).

**Comment by floradanna** [comment]
WP3 decision:
1. add the recommandation about manual linking to pages into the "contribution guidelines"
2. decide tagging system at the editorial meeting
3. define a system to manage sub-pages at the editorial meeting
