### ISSUE TITLE
Main RDM lifecycle image shrinking

### ISSUE THREAD

**Issue by CaroleGoble** [elixir-europe/rdm-toolkit#256]
**Describe the bug**
Using Firefox, when I do full screen the RDM lifecycle picture shrinks and never recovers unless I refresh the window

**To Reproduce**
1. Browser Firefox
2. Select "full Screen" icon
3. image shrinks

**Expected behavior**
Image doesn't shrink

**Screenshots**
![image](https://user-images.githubusercontent.com/7300655/101611522-85da8100-3a01-11eb-94b7-35d6ac6e8e52.png)

**Desktop (please complete the following information):**
 - OS: [windows]
 - Browser: firebox
 - Version [dunno]

**Comment by bedroesb** [comment]
@CaroleGoble thank you for notifying! @martin-nc is working on a fix :)
