### ISSUE TITLE
Update Your Problem - Sharing

### ISSUE THREAD

**Issue by elinkronander** [elixir-europe/rdm-toolkit#263]
**Link to the page of interest**
https://rdm.elixir-europe.org/data_sharing.html

**Describe what you would change to the page**
I would like to change the formatting to comply to the template and add additional content.

The first two questions I would like to add and answer are:

- Which repository should I use to share my data?
- How do I prepare for my data for sharing?

**Comment by floradanna** [comment]
Hi Elin, Thank you for your suggestion. 
Feel free to start editing the page and create your Draft Pull Request ([more information in the guide](https://rdm.elixir-europe.org/github_way.html)).

Please, let me know if you have any questions.

**Comment by elinkronander** [comment]
@floradanna I have created a draft-PR now, will continue working on this during next week (probably second half of the week)

**Comment by elinkronander** [comment]
There are some sections that I am still hesitating about on this page (see below), maybe you as editors has a clear picture of what goes where and what is meant to be on a _your problem_ page.

- The list of links to repositories
- Related topics
- External links

**Comment by floradanna** [comment]
* The list of links to repositories
Repositories already present in well established lists, such as [ELIXIR Deposition Databases for Biomolecular Data](https://elixir-europe.org/platforms/data/elixir-deposition-databases) and [Recommended Repositories by Scientific Data Nature](https://www.nature.com/sdata/policies/repositories), should **NOT** be all listed singularly again in our tool table, _unless additional information about the use of a repository is added in the text of the page_ (see EGA in your case). 
This is for minimising redundancy and reduce number of links. So, only well established lists of repositories should be added to the tool list and avoid listing each repository separately (unless specifically described in the text of the page).
[Here there are the instructions to add tools and resources in our table.](https://rdm.elixir-europe.org/tool_resource_update.html#making-changes) Please, check if your tool or resource is already present in the list before adding it.
* Related topics
"Related topics" will be removed from your problem page template, so you should leave it empty.
* External links
Under "external links" you can list references that you used in the page and useful links to other websites or pages (different from this rdm toolkit).

**Comment by floradanna** [comment]
@elinkronander Thanks for your contribution!
Please, notice that general considerations about data sharing (different reasons and ways to share based on data type) are described in [Data Life Cycle - Sharing](https://rdm.elixir-europe.org/sharing), so feel free to improve this page as well and reduce possible redundant information in this "Your Problem page - Data publication".
Let me know if you have any question.
