### ISSUE TITLE
Change name of page data_sustainability (Your problem)

### ISSUE THREAD

**Issue by YvonneKallberg** [elixir-europe/rdm-toolkit#265]
**Describe the bug**
Not quite a bug, but a report on inconsistency between web and underlying GitHub file. Your problem - Data Sustainability has changed name to Data Quality, and this should be reflected in the github repo name of the page (is currently data_sustainability.md).

**Comment by bedroesb** [comment]
This should be fixed yesterday, thank you for notifying!
