### ISSUE TITLE
Adding tools in the "tools and resources table"

### ISSUE THREAD

**Issue by floradanna** [elixir-europe/rdm-toolkit#276]
**Link to the page of interest**
All pages, especially the recently updated, mention tools and resources that are NOT in the "tool & resource list".

**Describe what you would change to the page**
Add tools and resources mentioned in pages in the "tool & resource list".

**List the tool(s)or resource(s) that are missing on the page (if applicable)**
Tools and resources mentioned in "Your problem" pages that are not in the "tool & resource list" (until today).

DMPTool | dmp
Argos | dmp
Bulk Rename Utility | data organisation
Renamer4Mac | data organisation
e!DAL | storage
Research Data Management Platfor (RDMP) | storage
ELIXIR Deposition Databases for Biomolecular Data | data sharing
Nature Scientific Data Recommended Data Repositories | data sharing
Annotare | metadata, data sharing
ENA Sample Checklists | metadata, data sharing
Digital Curation Center (DCC) metadata list | metadata
re3data.org | data sharing
Open Definition Conformant Licenses | data licence
Creative Commons License Chooser | data licence
Licence Selector | data licence
Choose a license | data licence
4TU.Datacentrum | data sharing
Dryad Digital Repository (in Scientific data) | data sharing
Figshare (in Scientific Data) | data sharing
Harvard Dataverse (in Scientific Data) | data sharing
Mendaley Data (in Scientific Data) | data sharing
Open Science Framework (in Scientific Data) | data sharing
Zenodo (in Scientific Data) | data sharing
Code Ocean | data sharing
REDCap | data quality
Pentaho Community Edition (CE), | data quality
Talend Open Studio. | data quality
Open Refine | data quality
Metrics for the evaluation of FAIRness | compliance
FAIR Data Maturity Model. Specification and Guidelines | compliance
FAIR evaluators | compliance
21 CFR part 11 | compliance
ISO 27001 | compliance
ISO/IEC 27018 | compliance

**Comment by floradanna** [comment]
I notice that repositories already present in well established lists, such as ELIXIR Deposition Databases for Biomolecular Data and Recommended Repositories by Scientific Data Nature, are again all listed singularly in our toolkit creating redundancy. Maybe we could consider mentioning only the well established lists and avoid listing all repositories (unless needed for domain specificity).

Maybe it is also worth to check if tools & resources in the "tools and resources table" are actually mentioned in a specific context in the toolkit or not.

**Comment by floradanna** [comment]
These tools and resources have been added to the [Goggle Spreadsheet](https://docs.google.com/spreadsheets/d/16PkQsXPfWbORwtHPu5jfM_VHyyBUVlQBiGkECjWpT6A/edit#gid=225416800) that will be used by editors to keep the overview of tags and keywords.

The listed tools and resources need to be properly tagged.

**Comment by bedroesb** [comment]
Yesterday in the WP3 meeting is decided that we will not list all databases in the toolkit but link to the  established lists.
