### ISSUE TITLE
Edit Your domain - Human data

### ISSUE THREAD

**Issue by nicjar** [elixir-europe/rdm-toolkit#280]
**Link to the page of interest**
https://rdm.elixir-europe.org/human_data

**Describe what you would change to the page**
- Edit and expand some of the content.
  - **Discussion point**: Should we focus scope to human genomic data?
    - If so, I still think we can some general content, but add some recommendations that are specific for genomic data.
- Possibly make sub-pages for the different sections

Also, the links in menus now go to a non-existent `humandata_usecase` page

**Comment by bedroesb** [comment]
@nicjar The menu and page names are getting fixed in PR #278. Thank you for telling!

**Comment by nicjar** [comment]
@bedroesb I have removed the content in #283 that was connected to this issue. Best to remove the link between them I think. I have started another draft PR (#307) for this issue

**Comment by nicjar** [comment]
Can we re-open this, as it is not solved by #283? Thanks!
