### ISSUE TITLE
Your domain links in side menu needs update

### ISSUE THREAD

**Issue by YvonneKallberg** [elixir-europe/rdm-toolkit#284]
**Describe the bug**
'_usecase' needs to be removed in the links in the Your problem side menu, since the pages seems to have been renamed.

**Comment by bedroesb** [comment]
Hello @YvonneKallberg , can you give a screenshot or a specific example because yesterday everything was renamed and _usecase should not be present anymore. Maybe reloading the page can help?

**Comment by YvonneKallberg** [comment]
Indeed, everything is working now, you can close this issue.

I was a bit early perhaps, I tried reloading previous to writing the issue but when that didn't help, I wanted it to be noted so that I could forget about it instead of having to check again later if fixed :-)

**Comment by bedroesb** [comment]
Tank you for keeping an eye on it ;) lots of things (especially names and tagging) changed yesterday, so if you see something, keep us updated !
