### ISSUE TITLE
Typo when tools and resources rendering is using 'error message'

### ISSUE THREAD

**Issue by YvonneKallberg** [elixir-europe/rdm-toolkit#289]
**Describe the bug**
In e.g. page [Data Quality](https://rdm.elixir-europe.org/data_quality.html), the {% include toollist.html tag="data quality" %} is displayed as `The tag “data quality” has not yet related tools are resources.` This 'error message' has a typo, it should be The tag “data quality” has not yet related tools **or** resources.

**Comment by bedroesb** [comment]
Thank you for notifying! This typo is fixed
