### ISSUE TITLE
Decide on a RDM life cycle design

### ISSUE THREAD

**Issue by martin-nc** [elixir-europe/rdm-toolkit#29]
We agreed to have a RDM life cycle diagram on the home page. I've had a look at some designs and put them in a doc. Note that some are just generic 'life cycle' diagrams and don't relate to data: https://docs.google.com/document/d/1k8WR3ZXt0T4uNB1EAsmR1h1MJL-SEfJIvODnKiYIHE4/edit?usp=sharing
Feel free to comment or add more.

We need to bear in mind:

-  https://github.com/elixir-europe/rdm-toolkit/issues/6 i.e. the diagram needs to be used in miniature as a navigation aid as well. 
- Icons might be nice (not all designs include them).
- The site will probably not contain many attractive photographs and illustrations, so maybe a more colourful diagram would be better? We could colour-code sections of the site and cheer up the text-heavy pages!
- We can make the diagram interactive - Jacek and I got one working last week, and Jacek has found a neat way of embedding the SVG without cluttering up the home page code.

**EDIT: ** this is a separate issue to the life cycle diagram content, dealt with here: https://github.com/elixir-europe/rdm-toolkit/issues/28.

**Comment by martin-nc** [comment]
In case discussions about design and icons get bogged down, then I've created a couple to just get started with and swap out when needed. They really don't take long to make. The small navigation icon is in the top right of each.

![rdm-lifecycle-sections](https://user-images.githubusercontent.com/15261745/87032289-4999bf00-c1dc-11ea-8b4e-9d31052e8bd6.png)

- Less space for icons
- When you roll over each stage then text describing the stage (the content you'll find in the website about it) could appear in the middle of the circle.
- The mini-navigation icon is not so clear - did a couple of variations but might be able to improve them.

![rdm-lifecycle-pie-chart](https://user-images.githubusercontent.com/15261745/87031764-78fbfc00-c1db-11ea-899b-f81882448bc7.png)

- A more basic one from last week.
- More space for icons?
- Clearer mini-navigation.
- I don't think the big version is as nice as the first version, but that's maybe just me!

Anyway, these are just some ideas to get started with, if we need them.

**Comment by korbinib** [comment]
Added a few more to the google doc.

- I would strongly vote for icons (maybe from the standard ELIXIR set to have a stronger branding?)

- The circular arrow design is cleaner and less noisy to the observer

- +1 for an interactive SVG

**Comment by martin-nc** [comment]
For icons, the Hub has an account with the Noun Project: https://thenounproject.com/. We can choose some from there. 

I don't think there are brand icons for the things in the RDM diagram. We only have standard icons for things like Platforms and Communities. I can check, though.

**Comment by korbinib** [comment]
Do you think something like this would work?
We could match it with colour matching info boxes on the stages with the icons. (like: https://www.mun.ca/cio/imp/images/content/imlcgraphic77.png) 

![RDM_cycle](https://user-images.githubusercontent.com/58505673/87298262-305d7f00-c50a-11ea-9d25-bc5fcb230e59.png)

**Comment by korbinib** [comment]
Added 7th stage

![RDM_cycle7](https://user-images.githubusercontent.com/58505673/87311552-ac15f680-c51f-11ea-9f84-d85a3c7ab377.png)

**Comment by bedroesb** [comment]
I kinda still like the 'old' styling from here:
http://dev.elixir-europe.org/rdmtoolkit-home/images/rdm-lifecycle-sections.svg ?

Since the icons are not really meaningful on there own, I liked the titles in the arrows horizontal with the arrows thicker and nicely fitting into eachother ....

**Comment by bedroesb** [comment]
or we add the icons above the titles in the arrows? don't know if it all will fit space whise

**Comment by korbinib** [comment]
![RDM_cycle4](https://user-images.githubusercontent.com/58505673/87325449-bfca5880-c531-11ea-8068-2b6489d646cd.png)
![RDM_cycle3](https://user-images.githubusercontent.com/58505673/87325458-c22cb280-c531-11ea-98bc-ceae5505cadf.png)
With terms in the arrows and optional more subtile icons

**Comment by bedroesb** [comment]
With trying it out myself in illustrator I discovered it is not easy to have the icons fitting on the same place, even if the arrows are fatter...
![image](https://user-images.githubusercontent.com/44875756/87332904-a11d8f00-c53c-11ea-8ba9-321e81f24905.png)

**Comment by korbinib** [comment]
I think we should just decide for one. I kind of like icons, also since we can use the EBI iconset (as for the platform icons) and create a bit of a recognition effect.

Guess we should stick to BE: Analyse (instead of AE: Analyze)?

**Comment by nsoranzo** [comment]
N. 9 in https://docs.google.com/document/d/1k8WR3ZXt0T4uNB1EAsmR1h1MJL-SEfJIvODnKiYIHE4/edit?usp=sharing has reasonable icon+text inside IMHO. But all the ones in this page work for me, nice work!

**Comment by bedroesb** [comment]
![image](https://user-images.githubusercontent.com/44875756/87351811-44c96800-c55a-11ea-9e0e-38c71fbc6f77.png)

**Comment by martin-nc** [comment]
How about moving the text closer to the icons so that they more obviously relate to each other? In some of these sections the icon and text seem to be floating independently to me. Also, maybe try a consistent relationship between the icon and the text, with the spacing the same for each section e.g. the icon is always above the text or the icon is always below, but the space between is the same for each icon/text pair. This might make a more structured pattern for your eye to follow. Something like this (roughly!):
![rdm-bert-modifications](https://user-images.githubusercontent.com/15261745/87355001-7f7dd100-c557-11ea-817f-f43b2f9f5f53.jpg)

Not sure if that's better? 

Having seen all these versions, though, I'm not sure if the icons are really necessary. The words are the most important thing for the user to see: the icons aren't self-explanatory enough for me. But I don't have particularly strong feelings about that. See what others think.

**Comment by bedroesb** [comment]
I think it is an improvement! Now that I start to understand csv, I can try that :)

**Comment by korbinib** [comment]
That's great! I like having icons, but I don't think they are essential.

**Comment by bedroesb** [comment]
![image](https://user-images.githubusercontent.com/44875756/87357571-82cb8980-c564-11ea-9991-af30e5b770aa.png)

**Comment by martin-nc** [comment]
Maybe use the same font as the rest of the page, too? If the SVG has some embedded style rules then make sure the font-family is set to Lato:
```
<style type="text/css">
  svg {font-family: 'Lato', sans-serif;font-variant-ligatures: none;}  
</style>
```
You can always insert this block just after the `<svg>` tag, if it's not there. You might have to remove the inline font-family declarations, though, if there are any. Anyway, just a thought...if you haven't had enough of it yet!

Another functionality I thought of, but not for this round of development: put a simple script it that showed you some short text in the middle of the circle when you hovered over a section of the circle. So if you hovered over 'Plan', you got the heading 'Plan' (in purple) in the middle of the circle, and a short sentence to say what you'll find if you click the 'Plan' section. This would only be for devices with a hover/mouseover event (i.e not mobiles). But again that's not for now!

**Comment by bedroesb** [comment]
The suggested changes are done in PR #55 

I will maybe open a separate issue on the idea of texts in the diagram
