### ISSUE TITLE
Add PR template and CONTRIBUTING.md

### ISSUE THREAD

**Issue by nsoranzo** [elixir-europe/rdm-toolkit#3]
https://docs.github.com/en/github/building-a-strong-community/creating-a-pull-request-template-for-your-repository

CONTRIBUTING.md should reference the licenses for content (CC-BY) and for infrastructure (MIT).

**Comment by bedroesb** [comment]
@pinarpink I moved the How to contribute page to the root of the directory and named it CONTRIBUTING.md, just like github prefers. It still ends up in the website at the same place

**Comment by pinarpink** [comment]
@bedroesb ok.

**Comment by nsoranzo** [comment]
@bedroesb I think `CONTRIBUTING.md` should be something that can be properly visualised inside GitHub, i.e. straight GitHub-flavoured Markdown. I'd suggest to revert the change and put in CONTRIBUTING.md:
- some details on how to contribute to the website infrastructure, and the licenses as mentioned in this issue;
- a link to the https://rdm.elixir-europe.org/how_to_contribute.html for how to contribute to the website content.

**Comment by bedroesb** [comment]
I reverted my changes to the original. CONTRIBUTING.md is something for on the to do list.

**Comment by nsoranzo** [comment]
Thanks!
