### ISSUE TITLE
Create a template for Team 4's best practice guidelines

### ISSUE THREAD

**Issue by martin-nc** [elixir-europe/rdm-toolkit#30]
We need to have a nice template for Team 4's best practice guidelines: https://drive.google.com/drive/folders/1Nx4ZWYQVnGeZ5etHoFZ3_ftB66Ru7o5q

This will allow us to see how they work as web pages, and to start filling out the content of the site. 

**Note:**  Remember that 'practice' is a noun and 'practise' is a verb! So 'We follow best practices' vs 'I practise the piano'.

**Comment by floradanna** [comment]
Possible template for pages in RDM_cycle: https://github.com/elixir-europe/rdm-toolkit/pull/66
