### ISSUE TITLE
Styling refinements

### ISSUE THREAD

**Issue by bedroesb** [elixir-europe/rdm-toolkit#49]
- [x] Center data life cycle diagram
- [x] Fix font in data life cycle diagram
- [x] maximum width of tables same as main text
- [x] first column with tool names wider so name fits
- [x] 4 buttons home screen wider 
- [x] remove/remap edit me button in all tools page
- [x] margin problem buttons sidepanel, small shift in sublevel when opening toplevel
- [x] take away link icons in 4 buttons home page
- [x] color of H3 titles
- [x] better spacing between sidenav
- [x] fixing problem with icon in the life cycle diagram (make them non clickable)
- [x] fixing html ugliness in generated pages
- [x] fix white space under footer on index page because of the unfolding flexboxes
- [x] Dots of lists in same blue as H2
- [x] better image margins in content

**Comment by bedroesb** [comment]
Dots in blue suggestion:
```
ul {
  list-style: none;
  margin-left: 2.5em;
}

ul li::before {
  content: "\2022";
  color: var(--accent-color);
  font-size: 1.2em;
  display: inline-block;
 /* Add margins as needed. */
}
```

**Comment by martin-nc** [comment]
Actually we can do this more simply by using the `::marker` pseudo-element:
```
ul li::marker {
  color: var(--blue-xx-dark);
}
```
The browser for `::marker` seems pretty good these days. The lists in the summary boxes seem a bit odd to me: they don't have any space to the left and perhaps the font goes a bit small. Can I suggest a slight refactor?
```
#toc {
  padding: 15px;
  background: var(--light-grey);
  margin: 1.5em 0;
  border-radius: 5px;
  font-size: 14px;
}

/* Indent the lists and reset any other padding */
#toc ul {
  padding: 0 0 0 20px;
}

/* Consistent vertical space between list items */
#toc li, #toc ul ul li {
  margin: 7px 0 0 0;
}

/* Sublists */
#toc ul ul {
  list-style: circle outside;
}

/* Responsive style to replace static width */
@media only screen and (min-width: 990px) {
    #toc {
        max-width: 50%;
    }
}
```
Here is a screenshot:
<img width="687" alt="Screenshot 2020-09-23 at 19 28 58" src="https://user-images.githubusercontent.com/15261745/94055390-c6e4d100-fdd4-11ea-898f-8403c6b9d348.png">

I've kept the default circle bullet points but we can change that (with `list-style-type` or `li::marker {content: "whatever";}`). I think they're okay as they are. I don't think the heading 'Table of contents' is needed, either. Anyway, these are just suggestions, so see what people think.

Incidentally, could we just use Bootstrap classes on the table of contents box, like 'container bg-light'? Either way,  if there are any other grey boxes on the site then it would be good to re-use any style we settle on here (for background colour, border-radius and padding). That would keep things consistent. Ideally we'd have a generic class for 'box' (with padding and border-radius), then one for 'bg-grey' or 'bg-blue' for grey and blue box backgrounds etc so we can combine classes to create consistent boxes. Not sure if that's possible in the template, though.

**Comment by bedroesb** [comment]
@martin-nc in #79 I applied your suggestions of the TOC. I just also added a max-width to the TOC on mobile level to distinguish it more from the navigation 'buttons' . On you last part: I agree that would make the css a lot easier to use. But If I am honest, the whole css part needs a total overhaul... This theme is clearly an opensource project with lac of vision by one person. people just keep adding there own classes overwriting the other ones... There are already many things I threw out with better results in the end :) I will put it on the long term to do list!

**Comment by bedroesb** [comment]
@martin-nc `::marker` is only available since chrome 86, explains why I don't see any effect!

**Comment by martin-nc** [comment]
Ah, looks like it's not ready for production yet, then. I read an article somewhere suggesting is was (maybe the Mozilla site). Anyway, CanIUse gives it patchy support: [https://caniuse.com/?search=%3A%3Amarker](https://caniuse.com/?search=%3A%3Amarker). That's a shame. It looks like a really useful pseudo-element. I guess we should go back to the `::before` pseudo-element, then.

**Comment by bedroesb** [comment]
@martin-nc or we implement it with ::marker (I also like the implementation) , and browsers will follow anyway within the upcoming months (chrome its latest release has it too, but not yet everywhere deployed). Browsers that don't have it will show it in black, which is not a super huge deal I think.  I applied it on the website, and indeed on firefox it looks good!

**Comment by martin-nc** [comment]
@bedroesb Yes, why not? Live on the edge!
