### ISSUE TITLE
Landing page

### ISSUE THREAD

**Issue by frederikcoppens** [elixir-europe/rdm-toolkit#5]
What should be on the first page ? Different layout ? 
Brief description of the goals
Structure of the information (tiles?)

**Comment by martin-nc** [comment]
My take:  

- what the toolkit is (i.e. what it contains)
- a few bullet points of benefits for the user (how the site helps the user)
- RDM life cycle diagram that is interactive, to navigate the site. The menu will also contain the same links once you move from the home page. Keep the vocabulary consistent!
- a contact for help or queries?
- Are we ready for user personal tiles?

**Comment by bedroesb** [comment]
I would also add an introduction text that is welcoming the visitor and gives some basic info about the website. 

Only text right now is "Find resources by clicking on the RDM data lifecycle"

**Comment by bedroesb** [comment]
We would close this issue and reopen more specific feature issues about the landing page.
