### ISSUE TITLE
Merge tools and resources tables

### ISSUE THREAD

**Issue by floradanna** [elixir-europe/rdm-toolkit#75]
@bedroesb The editorial board decided to DO NOT separate tools and resources. We would like to have only ONE table with "tools and resources" together.

**Comment by bedroesb** [comment]
Any visions on how we will link to bio.tools are fairsharing? One common column  or two seperate once. And do we label them different?

**Comment by nsoranzo** [comment]
We could have a "Registries" column that would contain different linking icons for bio.tools, FairSharing and any future registry we might decide to include in the future.
