### ISSUE TITLE
Delete "Summary" from all pages

### ISSUE THREAD

**Issue by floradanna** [elixir-europe/rdm-toolkit#76]
The editorial board would like to delete the "summary" from the metadata in all pages. Is there a way of deleting "summary" in bulk from all pages?

**Comment by bedroesb** [comment]
The summary was being used as description when the tagged pages are being listed, are we sure?

**Comment by pinarpink** [comment]
Summary is  a bit of. distraction for the short pages. But it is useful for long pages. @bedroesb I suggest that we make the summary box **hidden by default**. Only if the page author provides a summary it should show.

**Comment by bedroesb** [comment]
okay, I will take the empty ones away :)

**Comment by bedroesb** [comment]
I am just wondering how we will list the tagged pages in an informative way: https://elixir-europe.github.io/rdm-toolkit/research_it.html If the storage page here would have a summary, the user would know already what the page storage is about
