### ISSUE TITLE
Editorial board - editor in chiefs - CODEOWNERS

### ISSUE THREAD

**Issue by frederikcoppens** [elixir-europe/rdm-toolkit#8]
Set up the editorial board in GitHub (Team?)
Aim is to assign reviewing of new content to a group of people to ensure consistency across the  site

**Comment by frederikcoppens** [comment]
TASKS 

Set a house style
Overseeing tagging https://github.com/fair-cookbook/the-fair-cookbook/labels 
Monitoring and responding to update requests - either pull requests or emails - in a timely, visible and responsive manner. That means also letting contributors know that their request has been addressed
Entering into editorial discussions with contributors to adhere to house style and revise content
Check content works in ALL browsers

**Comment by nsoranzo** [comment]
> Set up the editorial board in GitHub (Team?)
> Aim is to assign reviewing of new content to a group of people to ensure consistency across the site

If we organise content in folders, we can use a `CODEOWNERS` file to automatically ask the mentioned owners to review PRs touching a specific folder.

**Comment by bedroesb** [comment]
This will start from #64
