### ISSUE TITLE
Template for functional areas/ your problem

### ISSUE THREAD

**Issue by bedroesb** [elixir-europe/rdm-toolkit#82]
At this moment there is no template for [functional areas](https://github.com/elixir-europe/rdm-toolkit/tree/master/pages/functional_areas). Do we need one? maybe a generic one that people can just copy around and with some basic guides

**Comment by pinarpink** [comment]
If we can have one generic for all, that would be ideal.

**Comment by pinarpink** [comment]
This appears to have been addressed by https://github.com/elixir-europe/rdm-toolkit/pull/99

**Comment by floradanna** [comment]
A template has been added: https://github.com/elixir-europe/rdm-toolkit/blob/master/pages/functional_areas/TEMPLATE_functional_areas.md.

In the "functional areas" folder there is the [data_managemet_planning](https://github.com/elixir-europe/rdm-toolkit/blob/master/pages/functional_areas/data_management_planning.md) page that is not yet shown in the toolkit website. Shall we add the correct permalink already?
Should additional pages be added in "your problem" section of the toolkit website before contentathon?

**Comment by bedroesb** [comment]
This indeed has to be done, but I was wondering how this will interfere with the existing planning page + I see there is not yet a correct use of the tool list part

**Comment by bedroesb** [comment]
Template is present @ pages/your_problem
