### ISSUE TITLE
Create issue templates

### ISSUE THREAD

**Issue by pinarpink** [elixir-europe/rdm-toolkit#85]
At least two templates are needed.

- Request/propose new page 
- Fix existing page

**Comment by pinarpink** [comment]
@bedroesb  as I do not have privileges, I created two templates [here](https://github.com/pinarpink/rdm-toolkit/issues/new/choose). we can start with these and improve.

**Comment by bedroesb** [comment]
@pinarpink I will make the additional template

**Comment by pinarpink** [comment]
@bedroesb OK
