### ISSUE TITLE
Search results are not clickable in mobile mode

### ISSUE THREAD

**Issue by bedroesb** [elixir-europe/rdm-toolkit#92]
In mobile mode or reduced window size, the search results are not clickable 

1) resize the window of your browser until the hamburger menu appears
2) go to the hamburger menu
3) type something in the searchbox
4) try to click on the results

tested on edge windows (chrome) and android

**Comment by martin-nc** [comment]
@bedroesb the `ul#results-container` has a z-index of -1, which means it lies behind the navbar container, and so is not clickable. The results container needs to have at least equal z-index to the navbar.

Incidentally, I see the navbar container has the `overflow-y` property set to `auto`. This means that if any content is too big for the container vertically (like the search dropdown) it will cause a scroll bar to appear. Do we want that, or do we want the dropdown to go outside the navbar box, so you don't have to scroll? Not sure which is cleaner. I think I prefer the dropdown box going outside the navbar, which means `overflow-y` will be `visible`. This is the default, actually, so you could just remove the whole `overflow` line for that to happen.
