### ISSUE TITLE
Trial for a adding New content

### ISSUE THREAD

**Issue by smza** [elixir-europe/rdm-toolkit#93]
**Write about the topic you are proposing**
This is about the testing the contractors guide

**Are there existing pages in the RDM toolkit website related to the requested page?**
No there are related pages existing on the website.

**Resources**
If there are there resources that could be utilised for writing the new page, please list them below:

**Context**
If this request is coming from a particular project, domain, or use-case please list them below:

**Comment by smza** [comment]
is this topics relevant?

**Comment by bedroesb** [comment]
Hello @smza, I created a trail page for you at https://rdm.elixir-europe.org/trial_page.html. More information  can be found in  the github way in the contribute section.
