### ISSUE TITLE
Flowcharts not readable

### ISSUE THREAD

**Issue by pinarpink** [elixir-europe/rdm-toolkit#97]
**Describe the bug**
Text in flow charts in the Github way and google doc way pages are not readable. 

**Expected behavior**
It should be possible to click on the chart to have a zoomed-in view.

**Additional context**
Reported by @smza

**Comment by bedroesb** [comment]
this was fixed in #88 :) can you check if this is still the case?

**Comment by bedroesb** [comment]
In this PR + the demo page I explain the click tag in case we want to make future pictures clickable :)

**Comment by bedroesb** [comment]
the fact that this happens in mobile mode, is for sure a bug that still needs to be fixed ;) 
![image](https://user-images.githubusercontent.com/44875756/94868320-3e54d900-0443-11eb-9e6a-2ac898629724.png)

**Comment by pinarpink** [comment]
It does indeed work. Thanks @bedroesb
